environment:

  matrix:

    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64

    - PYTHON: C:\Python38-x64
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 64

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - python --version
  - pip install setuptools coverage numpy scipy openpyxl networkx pandas matplotlib plotly nose utm folium
  - "echo %PATH%"
  - "python setup.py develop"
  - python --version

build: off

test_script:
  - "nosetests -v --nologcapture wntr"
