[build-system]
requires = ["setuptools", "numpy>=1.21,<2.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = ["time_consuming:excluded from ci quick test"]
addopts = "--doctest-modules"
